/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sienna Castro (https://sketchfab.com/siennacb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-cup-2e7a7a18bdec4abe81abd2e9b364ea27
Title: Coffee Cup
*/

import { Decal, Html, PerspectiveCamera, RenderTexture, Text, useGLTF, useTexture } from '@react-three/drei'
import { Texture } from 'three'
import * as THREE from 'three'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
export function CupViewer(props: any) {
    
  const { nodes, materials }: any = useGLTF('/3D/cup.glb');
  const decalTexture = useTexture("/3D/cup_decal.png") as Texture;
  decalTexture.colorSpace = THREE.SRGBColorSpace; 

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[-1.499, 37.641, -1.48]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[45, 45, 36.547]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cup_white-ceramic_0001'].geometry}
            material={materials['white-ceramic']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cup_white-ceramic_0_1'].geometry}
            material={materials['white-ceramic']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cup_white-ceramic_0_2'].geometry}
            material={materials.CoverCapGG}
          >
            <meshBasicMaterial transparent={true} opacity={0} />
                <Decal
                    // debug={true}
                    scale={[1.75, 1.75, 1.75]}
                    position={[0, -0.5, 0.25]}
                    rotation={[Math.PI / 2, 0, 0]}
                >
                    <meshBasicMaterial
                        map={decalTexture}  
                        transparent={true}
                        depthTest={false}
                        polygonOffset={true}
                        polygonOffsetFactor={-5}   // more negative = closer to camera
                                    />
                </Decal>
            </mesh>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coffee_coffee_0.geometry}
          material={materials.coffee}
          position={[0.926, 62.169, -1.543]}
          rotation={[-Math.PI / 2, 0, -0.694]}
          scale={98.704}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/3D/cup.glb')



